In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time as t
import csv
import random
import threading as th

In [3]:
# Chrome driver Path
chromepath= r"chromedriver.exe"

option= webdriver.ChromeOptions()      # open google chrome session

option.add_argument('-disk-cache-size= 3000000000')   # OPTIONAL,    --->  make memory cache size = 3000000000                                                                                                                                                                                                                                                                                                                         
driver= webdriver.Chrome(executable_path= chromepath, options= option)   # open driver

price_lst= []
details_lst= []
address_lst= []
spaces_lst= []
bedrooms_lst= []
bathrooms_lst= []
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++

for i in range(1,21):
    driver.get(f'https://aqarmap.com.eg/en/for-sale/villa/?default=20&page={i}')
    
    # scrape Prices:
    Price= driver.find_elements_by_css_selector("span[class= 'integer']")            
    Price_lst1= [element.text for element in Price if len(element.text) >= 6]
    price_lst.extend(Price_lst1)

    
    # scrape Details:
    details= driver.find_elements_by_css_selector("h2[class= 'search-listing-card__title']")            
    details_lst1= [element.text for element in details]
    details_lst.extend(details_lst1)

    
# scrape Address:
    address= driver.find_elements_by_css_selector("p[class= 'search-listing-card__address']")            
    address_lst1= [element.text for element in address]
    address_lst.extend(address_lst1)
    
    
# scrape ground space:
    containers= driver.find_elements_by_css_selector("div[class= 'search-listing-card__details__wrapper']")          
    for container in containers:
        spaces= container.find_element_by_css_selector("div[class= 'search-listing-card__attributes']").find_element_by_css_selector("label:nth-child(1)").text
        spaces_lst.append(spaces)

        
# scrape bedrooms:
    containers= driver.find_elements_by_css_selector("div[class= 'search-listing-card__details__wrapper']")          
    for container in containers:
        try:                         
            bedrooms= container.find_element_by_css_selector("div[class= 'search-listing-card__attributes']").find_element_by_css_selector("label:nth-child(2)").text
            bedrooms_lst.append(bedrooms)
        except:
            bedrooms_lst.append("")
    
    
# scrape bathrooms:
    containers= driver.find_elements_by_css_selector("div[class= 'search-listing-card__details__wrapper']")          
    for container in containers:
        try:
            bathrooms= container.find_element_by_css_selector("div[class= 'search-listing-card__attributes']").find_element_by_css_selector("label:nth-child(3)").text
            bathrooms_lst.append(bathrooms)
        except:
            bathrooms_lst.append("")
    
########################################################
    from itertools import zip_longest
    from csv import writer

    file_list= [price_lst, details_lst, address_lst, spaces_lst, bedrooms_lst, bathrooms_lst]
    exported= zip_longest(*file_list)

    with open(f'Villlla.csv', 'w', encoding="utf-8") as csv_file:
        wr= writer(csv_file)
        wr.writerow(['Price', 'Details', 'Address', 'Space', 'Bedroom', 'Bathroom'])
        wr.writerows(exported)

<ipython-input-3-3caccf35cb05>:7: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver= webdriver.Chrome(executable_path= chromepath, options= option)   # open driver

In [4]:
import pandas as pd

dataScience_jobs_csv= pd.read_csv('Villlla.csv')
print(dataScience_jobs_csv.shape)      # 199 jobs, 7 info about jobs

with pd.option_context('display.max_colwidth', None):
    display(dataScience_jobs_csv)

(300, 6)

,Price,Details,Address,Space,Bedroom,Bathroom
0,"2,900,000",Twin House For sale in Moon Hills,"مون هيلز, كمبوند في ٦ اكتوبر",256 M²,4.0,3.0
1,"4,290,000",Town House 218m for sale in Monte Napoleon - Mostakbal City,Mostakbal City,218 M²,3.0,4.0
2,"3,800,000",Separate Villa For sale in Moon Hills,"مون هيلز, كمبوند في ٦ اكتوبر",288 M²,5.0,4.0
3,"2,200,000",Villas For sale in Porto October,"بورتو اكتوبر, كمبوند في ٦ اكتوبر",155 M²,3.0,2.0
4,"13,500,000",Villas 600 m For sale in Obour City,"المرحله السابعه, إمتداد الرحاب",600 M²,7.0,5.0
...,...,...,...,...,...,...
295,"13,000,000",HOT DEAL Villa 3rd Row Bianchi - Sidi Abdelrahman,bianchi,346 M²,4.0,6.0
296,"4,255,000",Separate Villa For sale in Porto October,"بورتو اكتوبر, كمبوند في ٦ اكتوبر",200 M²,5.0,3.0
297,"9,241,000",Villas in SODIC East 251 M² Semi Finished For sale,"سوديك إيست, كمبوند فى هليوبوليس الجديدة",251 M²,4.0,3.0
298,"7,200,000",Middle Townhouse for sale 257m - Palm Hills,palm hills,257 M²,3.0,5.0
299,"6,000,000",Town House For sale in Hyde Park North Coast,"هايد بارك الساحل الشمالي, منتجعات الساحل الشمالى",175 M²,3.0,3.0